bundler_args: --without development
language: ruby
env: COVERAGE=on
script:
 - bundle exec rspec spec
rvm:
 - 1.9.2
 - 1.9.3
 - jruby-18mode
 - jruby-19mode
 - rbx-18mode
 - rbx-19mode
 - ruby-head
 - jruby-head
 - 1.8.7
 - ree
